version: '3.3'
services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8081:80"
    networks:
      - e-commerce-network
  
  product-catalog:
    build:
      context: ./product-catalog
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8082:80"
    networks:
      - e-commerce-network
  
  order-processing:
    build:
      context: ./order-processing
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8083:80"
    networks:
      - e-commerce-network

networks:
  e-commerce-network:
    driver: bridge