apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-front-end-deployment
  labels:
    name: front-end-deployment
    app: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      name: front-end-pod
      app: front-end
  template:
    metadata:
      labels:
        name: front-end-pod
        app: front-end
    spec:
      containers:
        - name: front-end
          image: maazpatel24/front-end:v1.0
          ports:
           - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: dev-front-end-service
  labels:
    name: front-end-service
    app: front-end
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    name: front-end-pod
    app: front-end

        
    