apiVersion: v1
kind: Service
metadata:
  name: dev-front-end-service
  labels:
    name: front-end-service
    app: front-end
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    name: front-end-pod
    app: front-end