apiVersion: v1
kind: Service
metadata:
  name: dev-order-processing-service
  labels:
    name: order-processing-service
    app: order-processing
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30100
  selector:
    name: order-processing-pod
    app: order-processing